### ISSUE TITLE
Catalyst mandlebrot miniapp test failure

### ISSUE THREAD

**Issue by burlen** [SENSEI-insitu/SENSEI#50]
The Catalyst script needs to be updated for newer version of Catalyst. Last known working version 5.8.1.
```
28/29 Test #28: testMandelbrotCatalyst ...................***Failed  Error regular expression found in output. Regex=[[Ee][Rr][Rr][Oo][Rr]]  3.38 sec
STATUS: [0][/work/SENSEI/sensei-svtk/sensei/ConfigurableAnalysis.cxx:671][v3.2.2-121-gc7c45770]
STATUS: Configured CatalystAnalysisAdaptor pythonscript /work/SENSEI/sensei-svtk/miniapps/mandelbrot/testing/mandelbrot_catalyst.py
Simulating time step: cycle=0, time=0 over domain -1.55, -0.2, -0.8, 0.55
Traceback (most recent call last):
  File "/work/SENSEI/PV-5.10.0-build/lib64/python3.10/site-packages/paraview/servermanager.py", line 496, in __setattr__
    setter(self, value)
  File "/work/SENSEI/PV-5.10.0-build/lib64/python3.10/site-packages/paraview/servermanager.py", line 2612, in setProperty
    return self.SetPropertyWithName(propName, value)
  File "/work/SENSEI/PV-5.10.0-build/lib64/python3.10/site-packages/paraview/servermanager.py", line 355, in SetPropertyWithName
    prop.SetData(arg)
  File "/work/SENSEI/PV-5.10.0-build/lib64/python3.10/site-packages/paraview/servermanager.py", line 866, in SetData
    convertedValues = list(map(self.ConvertValue, values))
  File "/work/SENSEI/PV-5.10.0-build/lib64/python3.10/site-packages/paraview/servermanager.py", line 984, in ConvertValue
    raise ValueError("%s is not a valid value." % value)
ValueError: AnyLocation is not a valid value.

During handling of the above exception, another exception occurred:
```

**Comment by c-wetterer-nelson** [comment]
Looks like you already fixed this one, removing that unnecessary default item.
